export const generalSettings = [
  {
    title: 'settings.general',
    description: 'settings.timezone_language',
    icon: 'settings',
    key: 'general',
    value: 'general',
    options: [
      {
        title: 'settings.timezone',
        description: '',
        key: 'app_time_zone',
        value: 'Kigali/Rwanda',
        type: 'select',
        options: [
          { key: 'Kigali/Rwanda', title: 'Kigali/Rwanda' },
          { key: 'Nairobi/Kenya', title: 'Nairobi/Kenya' },
          { key: 'Kampala/Uganda', title: 'Kampala/Uganda' },
        ],
      },
      {
        title: 'settings.language',
        description: 'settings.language_description',
        key: 'app_language',
        value: 'English',
        type: 'select',
        options: [
          { key: 'en', title: 'English' },
          { key: 'rw', title: 'Kinyarwanda' },
          // { key: "fr", title: "French" },
          // { key: "sw", title: "Kiswahili" },
        ],
      },
      {
        title: 'settings.theme',
        description: 'settings.theme_description',
        key: 'app_theme',
        value: 'system',
        type: 'select',
        options: [
          // { key: "System Default", title: "System Default" },
          { key: 'dark', title: 'Dark Mode' },
          { key: 'light', title: 'Light Mode' },
        ],
      },
    ],
  },
  {
    title: 'settings.information',
    description: 'settings.information_description',
    icon: 'info',
    key: 'information',
    value: 'information',
    options: [
      {
        title: 'settings.information_option_name',
        description: 'settings.information_option_name_description',
        key: 'business_name',
        value: 'Chez Lyz',
      },
      {
        title: 'settings.information_option_tin',
        description: 'settings.information_option_tin_description',
        key: 'TIN',
        value: '10078832',
      },
      {
        title: 'settings.information_option_type',
        description: 'settings.information_option_type_description',
        key: 'business_type',
        value: 'Butike',
        type: 'select',
        options: [
          { key: 'Boutique', title: 'Boutique' },
          { key: 'Hair Saloon', title: 'Hair Saloon' },
          { key: 'Restaurant', title: 'Restaurant' },
          { key: 'Bar', title: 'Bar' },
          { key: 'Phone Shop', title: 'Phone Shop' },
          { key: 'Car Wash', title: 'Car Wash' },
          { key: 'Others', title: 'Others' },
        ],
      },
    ],
  },
  {
    title: 'settings.contact',
    description: 'settings.contact_description',
    icon: 'contact-page',
    key: 'contact',
    value: 'contact',
    options: [
      {
        title: 'settings.contact_option_address',
        description: 'settings.contact_option_address_description',
        key: 'contact_address',
        value: 'Gikondo, Bwerankoli, Kigarama, Kicukiro, Kigali, Rwanda',
      },
      {
        title: 'settings.contact_option_person',
        description: 'settings.contact_option_person_description',
        key: 'contact_person',
        value: 'Bakomeza Mathias',
      },
      {
        title: 'settings.contact_option_phone',
        description: 'settings.contact_option_phone_description',
        key: 'contact_phone',
        value: '250788514836',
        keyboardType: 'numeric',
      },
      {
        title: 'settings.contact_option_email',
        description: 'settings.contact_option_email_description',
        key: 'contact_email',
        value: 'bavenus44@gmail.com',
        keyboardType: 'email-address',
      },
    ],
  },
  {
    title: 'settings.payments',
    description: 'settings.payments_description',
    icon: 'payments',
    key: 'payments',
    value: 'payments',
    options: [
      {
        title: 'settings.payments_option_currency',
        description: 'settings.payments_option_currency_description',
        icon: 'money-off',
        key: 'app_default_currency',
        value: 'USD',
        type: 'select',
        options: [
          { key: 'USD', title: 'USD' },
          { key: 'RWF', title: 'RWF' },
          // { key: "KES", title: "KES" },
          { key: 'UGX', title: 'UGX' },
        ],
      },
      {
        title: 'settings.payments_option_method',
        description: '',
        key: 'app_default_payment_method',
        value: 'Dukapp',
        type: 'select',
        options: [
          { key: 'Cash', title: 'Cash' },
          { key: 'mobile_mtn_momo', title: 'MTN MoMo' },
          { key: 'mobile_airtel_money', title: 'Airtel Money' },
          { key: 'mobile_m_pesa', title: 'M-Pesa' },
          { key: 'Credit', title: 'Credit' },
          { key: 'Debit Card', title: 'Debit Card' },
          { key: 'Others', title: 'Others' },
        ],
      },
    ],
  },
  // {
  //   title: "Tax",
  //   description: "Country Revenue",
  //   icon: "money",
  //   key: "tax",
  //   value: "tax",
  //   options: [],
  // },
  // {
  //   title: "Receipt",
  //   description: "Purchase Receipt",
  //   icon: "receipt",
  //   key: "receipt",
  //   value: "receipt",
  //   options: [],
  // },
  {
    title: 'settings.backup',
    description: 'settings.backup_description',
    icon: 'backup',
    key: 'backup',
    value: 'backup',
    color: '#15803d',
    action: 'backup_application',
    options: [],
  },
  {
    title: 'settings.seed',
    description: 'settings.seed_description',
    icon: 'data-usage',
    key: 'seed_db',
    value: 'seed_db',
    color: '#3f6212',
    options: [
      {
        title: 'settings.seed_option_boutique',
        description: 'settings.seed_option_boutique_description',
        key: 'boutique',
        value: 'Boutique data',
        action: 'handleDatabaseSeed',
      },
      {
        title: 'settings.seed_option_shop',
        description: 'settings.seed_option_shop_description',
        key: 'electronic_shop',
        value: 'Electronic Shop Data',
        action: 'handleDatabaseSeed',
      },
      {
        title: 'settings.seed_option_bar',
        description: 'settings.seed_option_bar_description',
        key: 'bar_restaurant',
        value: 'bar_restaurant',
        action: 'handleDatabaseSeed',
      },
      {
        title: 'settings.seed_option_coffee',
        description: 'settings.seed_option_coffee_description',
        key: 'coffee_shop',
        value: 'Coffee Shop Data',
        action: 'handleDatabaseSeed',
      },
    ],
  },
  {
    title: 'settings.reset_database',
    description: 'settings.reset_database_description',
    icon: 'delete',
    key: 'reset-db',
    value: 'reset-db',
    action: 'handleDatabaseReset',
    color: '#dc2626',
    options: [],
  },
  {
    title: 'settings.support',
    description: 'settings.support_description',
    icon: 'people',
    key: 'socialmedia',
    value: 'socialmedia',
    color: '#10B981',
    options: [
      {
        title: 'settings.support_option_twitter',
        description: 'settings.support_option_twitter_description',
        key: 'Twitter',
        value: 'Twitter',
        action: 'handlesocialmedia',
      },
      {
        title: 'settings.support_option_instagram',
        description: 'settings.support_option_instagram_description',
        key: 'Instagram',
        value: 'Instagram',
        action: 'handlesocialmedia',
      },
      {
        title: 'settings.support_option_linkedin',
        description: 'settings.support_option_linkedin_description',
        key: 'LinkedIn',
        value: 'LinkedIn',
        action: 'handleLinkedIn',
      },
    ],
  },
  {
    title: 'settings.logout',
    description: null,
    icon: 'logout',
    key: 'logout',
    value: 'logout',
    color: '#f59e0b',
    action: 'logout',
    options: [],
  },
];
