export const generalSettings = [
  {
    title: "General",
    description: "Timezone, Language...",
    icon: "settings",
    key: "general",
    value: "general",
    options: [
      {
        title: "Time Zone",
        description: "",
        key: "app_time_zone",
        value: "Kigali/Rwanda",
        type: "select",
        options: [
          { key: "Kigali/Rwanda", title: "Kigali/Rwanda" },
          { key: "Nairobi/Kenya", title: "Nairobi/Kenya" },
          { key: "Kampala/Uganda", title: "Kampala/Uganda" },
        ],
      },
      {
        title: "Language",
        description: "Select your language",
        key: "app_language",
        value: "English",
        type: "select",
        options: [
          { key: "en", title: "English" },
          // { key: "fr", title: "French" },
          // { key: "rw", title: "Kinyarwanda" },
          // { key: "sw", title: "Kiswahili" },
        ],
      },
      {
        title: "Theme",
        description: "Application Theme",
        key: "app_theme",
        value: "system",
        type: "select",
        options: [
          // { key: "System Default", title: "System Default" },
          // { key: "Dark Mode", title: "Dark Mode" },
          { key: "Light Mode", title: "Light Mode" },
        ],
      },
    ],
  },
  {
    title: "Information",
    description: "Business Name, Logo...",
    icon: "info",
    key: "information",
    value: "information",
    options: [
      {
        title: "Business Name",
        description: "Configure official company name",
        key: "business_name",
        value: "Chez Lyz",
      },
      {
        title: "TIN",
        description: "Tax Identification Number",
        key: "TIN",
        value: "10078832",
      },
      {
        title: "Business Type",
        description: "Saloon, Restorant, Butike..",
        key: "business_type",
        value: "Butike",
        type: "select",
        options: [
          { key: "Boutique", title: "Boutique" },
          { key: "Hair Saloon", title: "Hair Saloon" },
          { key: "Restaurant", title: "Restaurant" },
          { key: "Bar", title: "Bar" },
          { key: "Phone Shop", title: "Phone Shop" },
          { key: "Car Wash", title: "Car Wash" },
          { key: "Others", title: "Others" },
        ],
      },
    ],
  },
  {
    title: "Contact",
    description: "Phone, Address...",
    icon: "contact-page",
    key: "contact",
    value: "contact",
    options: [
      {
        title: "Address",
        description: "Update Company Address",
        key: "contact_address",
        value: "Gikondo, Bwerankoli, Kigarama, Kicukiro, Kigali, Rwanda",
      },
      {
        title: "Contact Person",
        description: "Shop Owner",
        key: "contact_person",
        value: "Bakomeza Mathias",
      },
      {
        title: "Phone",
        description: "Contact phone",
        key: "contact_phone",
        value: "250788514836",
        keyboardType: "numeric"
      },
      {
        title: "Email",
        description: "Contact email",
        key: "contact_email",
        value: "bavenus44@gmail.com",
        keyboardType: "email-address"
      },
    ],
  },
  {
    title: "Payments",
    description: "Payment Methods",
    icon: "payments",
    key: "payments",
    value: "payments",
    options: [
      {
        title: "Default Currency",
        description: "Payment Currency",
        icon: "money-off",
        key: "app_default_currency",
        value: "USD",
        type: "select",
        options: [
          { key: "USD", title: "USD" },
          { key: "RWF", title: "RWF" },
          // { key: "KES", title: "KES" },
          { key: "UGX", title: "UGX" },

        ],
      },
      {
        title: "Default Payment Method",
        description: "",
        key: "app_default_payment_method",
        value: "Dukapp",
        type: "select",
        options: [
          { key: "Cash", title: "Cash" },
          { key: "Mtn-Momo", title: "MTN MoMo" },
          { key: "Airtel-Money", title: "Airtel Money" },
          // { key: "mobile_m_pesa", title: "M-Pesa" },
          { key: "Credit", title: "Credit" },
          // { key: "Debit Card", title: "Debit Card" },
          { key: "Others", title: "Others" },
        ],
      },
    ],
  },
  // {
  //   title: "Tax",
  //   description: "Country Revenue",
  //   icon: "money",
  //   key: "tax",
  //   value: "tax",
  //   options: [],
  // },
  // {
  //   title: "Receipt",
  //   description: "Purchase Receipt",
  //   icon: "receipt",
  //   key: "receipt",
  //   value: "receipt",
  //   options: [],
  // },
  {
    title: "Backup",
    description: "Take Application Backup",
    icon: "backup",
    key: "backup",
    value: "backup",
    color: "#15803d",
    action: "backup_application",
    options: [],
  },
  {
    title: "Seed Database",
    description: "Add Default Data To Your Shop",
    icon: "data-usage",
    key: "seed_db",
    value: "seed_db",
    color: "#3f6212",
    options: [
      {
        title: "Boutique",
        description: "Seed Boutique data",
        key: "boutique",
        value: "Boutique data",
        action: "handleDatabaseSeed",
      },
      {
        title: "Electronic Shop",
        description: "Seed Electronic Shop",
        key: "electronic_shop",
        value: "Electronic Shop Data",
        action: "handleDatabaseSeed",
      },
      {
        title: "Bar & Restaurant",
        description: "Seed Bar and Restaurant",
        key: "bar_restaurant",
        value: "bar_restaurant",
        action: "handleDatabaseSeed",
      },
      {
        title: "Coffee Shop",
        description: "Seed Coffee Shop",
        key: "coffee_shop",
        value: "Coffee Shop Data",
        action: "handleDatabaseSeed",
      },
    ],
  },
  {
    title: "Reset Database",
    description: "Delete Application Database",
    icon: "delete",
    key: "reset-db",
    value: "reset-db",
    action: "handleDatabaseReset",
    color: "#dc2626",
    options: [],
  },
  {
    title: "Support us dukapp",
    description: "support the dukapp community and invest",
    icon: "people",
    key: "receipt",
    value: "receipt",
    options: [],
  },
  {
    title: "Log Out",
    description: null,
    icon: "logout",
    key: "logout",
    value: "logout",
    color: "#f59e0b",
    action: "logout",
    options: [],
  },
];
